keywords = [
    "fraud",
    "corruption",
    "scandal",
    "lawsuit",
    "investigation",
    "sanctioned",
    "violation",
    "illegal",
    "misconduct",
    "bribery",
    "money laundering",
    "criminal charges",
    "bankruptcy",
    "default",
    "penalty",
    "fine",
    "settlement",
    "complaint",
    "suspension",
    "revocation",
    "forfeiture",
    "blacklisted",
    "ban",
    "data breach",
    "privacy breach",
    "environmental disaster",
    "product recall",
    "workplace accident",
    "customer complaints",
    "securities fraud",
    "insider trading",
    "market manipulation",
    "regulatory violation",
    "insolvency",
    "embezzlement",
    "kickbacks",
    "conflict of interest",
    "false claims",
    "whistleblower",
    "discrimination",
    "harassment",
    "price fixing",
    "tax evasion",
    "counterfeit",
    "insider threat",
    "fraudulent activity",
    "intellectual property theft",
    "reputation damage",
    "ethical violation",
    "failure to comply",
    "safety violation",
    "cybersecurity breach",
    "consumer fraud",
    "illegal practices",
    "accounting fraud",
    "banned substances",
    "regulatory non-compliance",
    "professional misconduct",
    "money mismanagement",
    "insider misconduct",
    "unfair business practices",
    "fraudulent financial reporting",
    "contractual breach",
    "unauthorized transactions",
    "fraudulent billing",
    "misappropriation of funds",
    "unfair competition",
    "anti-money laundering violations",
    "foreign corrupt practices",
    "false advertising",
    "unlicensed operations",
    "unethical behavior",
    "bodily harm",
    "workplace violations",
    "insider threats",
    "supplier fraud",
    "fabricated documents",
    "fraudulent claims",
    "government investigation",
    "breach of fiduciary duty",
    "illegal payments",
    "unlawful activities",
    "product liability",
    "tax fraud",
    "economic espionage",
    "consumer safety",
    "insider abuse",
    "contract fraud",
    "environmental violation",
    "fraudulent schemes",
    "money misappropriation",
    "improper disclosure",
    "price manipulation",
    "whistleblower allegations",
    "contract irregularities",
    "insider trading",
    "violations of antitrust laws",
    "unfair labor practices",
    "unregistered securities",
    "fraudulent investments",
    "product tampering",
    "unethical practices",
    "exploitation of employees",
    "kickback schemes",
    "tax evasion",
    "insider knowledge",
    "failure to disclose",
    "manipulation of financial statements",
    "fraudulent sales",
    "regulatory penalties",
    "insider information",
    "government fines",
    "supplier misconduct",
    "conflicts of interest",
    "regulatory scrutiny",
    "improper accounting",
    "market misconduct",
    "violations of code of conduct",
    "consumer deception",
    "breach of contract",
    "improper lending practices",
    "fraudulent marketing",
    "insider influence",
    "insider dealing",
    "negligence claims",
    "regulatory non-compliance",
    "consumer harm",
    "unsafe products",
    "unreported income",
    "unlawful practices",
    "misrepresentation",
    "fraudulent activity",
    "dishonesty",
    "unfair trade practices",
    "data manipulation",
    "health and safety violations",
    "fraudulent loans",
    "market abuse",
    "confidentiality breach",
    "insider misconduct",
    "ethical violations",
    "employee misconduct",
    "insider threats",
    "market rigging",
    "breach of trust",
    "improper payments",
    "unauthorized access",
    "mismanagement",
    "violations of labor laws",
    "product defects",
    "unfair treatment",
    "unregistered products",
    "false statements",
    "fraudulent transactions",
    "misuse of funds",
    "insider collusion",
    "false certifications",
    "regulatory violations",
    "misleading advertising",
    "bribery allegations",
    "confidential information leak",
    "misuse of authority",
    "tax evasion schemes",
    "failure to supervise",
    "product failure",
    "insider trading schemes",
    "customer harm",
    "government penalties",
    "fraudulent schemes",
    "contract violations",
    "insider influence",
    "non-compliant practices",
    "fraudulent reporting",
    "counterfeit products",
    "misappropriation of assets",
    "market misconduct",
    "violations of company policies",
    "consumer harm",
    "improper sales practices",
    "improper conduct",
    "conflicts of interest",
    "unlawful transactions",
    "supplier misconduct",
    "fraudulent billing",
    "misrepresentation of qualifications",
    "accounting irregularities",
    "ethical breaches",
    "government fines",
    "data privacy violations",
    "unfair competition",
    "financial misconduct",
    "product safety concerns",
    "unauthorized use of funds",
    "insider collusion",
    "violations of privacy laws",
    "undisclosed conflicts of interest",
    "financial irregularities",
    "violations of trade regulations",
    "exploitation of vulnerable individuals",
    "disclosure failures",
    "insider dealing",
    "improper marketing practices",
    "product contamination",
    "unethical behavior",
    "abuse of power",
    "insider trading allegations",
    "non-compliance with regulations",
    "health and safety hazards",
    "employment discrimination",
    "product testing manipulation",
    "fraudulent claims processing",
    "market manipulation",
    "unfair business tactics",
    "fraudulent practices",
    "failure to disclose information",
    "customer data breaches",
    "government investigations",
    "contract irregularities",
    "insider abuse",
    "whistleblower allegations",
    "anti-competitive behavior",
    "tax avoidance",
    "failure to supervise employees",
    "market misconduct",
    "consumer complaints",
    "improper transactions",
    "fraudulent insurance claims",
    "bribery schemes",
    "contract fraud",
    "environmental violations",
    "money misappropriation",
    "unfair billing practices",
    "insider trading",
    "violations of ethical standards",
    "regulatory violations",
    "misuse of customer information",
    "fraudulent billing practices",
    "improper payments",
    "product quality issues",
    "unfair pricing",
    "accounting fraud",
    "unauthorized trading",
    "unfair labor conditions",
    "unlicensed operations",
    "fraudulent marketing tactics",
    "regulatory fines",
    "insider trading activity",
    "failure to comply with regulations",
    "consumer fraud",
    "unsafe working conditions",
    "insider abuse of information",
    "violations of safety standards",
    "employment violations",
    "fraudulent accounting practices",
    "misleading statements",
    "market abuse",
    "conflicts of interest",
    "regulatory investigations",
    "improper accounting practices",
    "market manipulation",
    "violations of code of conduct",
    "consumer deception",
    "unfair business practices",
    "breach of contract",
    "unlicensed operations",
    "fraudulent marketing",
    "insider influence",
    "insider dealing",
    "negligence"
]
